name: Integration file
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  api_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Run PowerShell script
        shell: pwsh
        run: |
          $commitSha = $env:GITHUB_SHA
          $branchName = $env:GITHUB_REF -replace 'refs/heads/',''
          echo "Commit SHA: $commitSha"
          echo "Branch Name: $branchName"
          $dif = git diff-tree --no-commit-id --name-only -r $commitSha
          echo $dif


      

          
        
        
        
